class States():
    main_state = "main_state"
    new_bot_state = "new_bot_state"
    upload_material = "upload_material"
    photo_price_state = "photo_price_state"
    video_price_state = "video_price_state"
    alert = "alert"
    find_user = "find_user"
    find_bot = "find_bot"
    change_balance = "change_balance"
    input_card_number = "input_card_number"
    input_withdrawal_amount = "input_withdrawal_amount"
    change_commission_percentage = "change_commission_percentage"
    change_referal_bonus = "change_referal_bonus"
    change_ref_in_user_bot = "change_ref_in_user_bot"
    start_referal_sum = "start_referal_sum"